### ISSUE TITLE
Updating to latest OpenJPH breaks encoder

### ISSUE THREAD

**Issue by jmhmd** [chafey/openjphjs#4]
When updating the OpenJPH submodule to the latest commit, test encoding throws the following error:

```
RuntimeError: null function or function signature mismatch
    at wasm://wasm/000a9b56:wasm-function[46]:0x94c
    at wasm://wasm/000a9b56:wasm-function[54]:0x129f
    at wasm://wasm/000a9b56:wasm-function[72]:0x2c5c
    at wasm://wasm/000a9b56:wasm-function[159]:0xff13
    at invoke_iiii (/workspaces/openjphjs/dist/openjphjs.js:1:60705)
    at wasm://wasm/000a9b56:wasm-function[185]:0x14b24
    at wasm://wasm/000a9b56:wasm-function[109]:0x75c1
    at HTJ2KEncoder.HTJ2KEncoder$encode [as encode] (eval at new_ (/workspaces/openjphjs/dist/openjphjs.js:1:36933), <anonymous>:8:1)
    at encode (/workspaces/openjphjs/test/node/index.js:42:15)
    at openjphjs.onRuntimeInitialized (/workspaces/openjphjs/test/node/index.js:63:3)
```

**Comment by aous72** [comment]
I suspect it is line 248 in ```openjphjs/src/HTJ2KEncoder.hpp```. 
```codestream.write_headers(&encoded_);``` signature has changed.  
This line should be ```codestream.write_headers(&encoded_, NULL, 0);```

give it a try and if it works. we need to change openjphjs

**Comment by aous72** [comment]
@jmhmd Please ignore my earlier comment.
There was a bug in the OpenJPH library; a function pointer was not set to its correct value -- it was set to NULL.
It compiles and run now.

**Comment by chafey** [comment]
Resolved with  https://github.com/chafey/openjphjs/pull/8
